version: "3.8"

services:
  frontend:
    image: docker.io/hikemalliday/checkers-react-frontend:dockerhub
    ports:
      - "5173:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_APP_HOST_NAME=${VITE_APP_HOST_NAME:-LOCAL}
  backend:
    image: docker.io/hikemalliday/checkers-react-backend:dockerhub
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
